/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module PROCESSOR(clock, reset, zero);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire [31:0] \IFU_module.PC ;
  wire [7:0] \IFU_module.instr_mem.Memory[0] ;
  wire [3:0] alu_control;
  input clock;
  input reset;
  output zero;
  sky130_fd_sc_hd__clkinv_1 _103_ (
    .A(reset),
    .Y(_009_)
  );
  sky130_fd_sc_hd__clkinv_1 _104_ (
    .A(\IFU_module.instr_mem.Memory[0] [5]),
    .Y(_027_)
  );
  sky130_fd_sc_hd__clkinv_1 _105_ (
    .A(\IFU_module.PC [2]),
    .Y(_000_)
  );
  sky130_fd_sc_hd__clkinv_1 _106_ (
    .A(\IFU_module.instr_mem.Memory[0] [7]),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nor2_1 _107_ (
    .A(alu_control[3]),
    .B(alu_control[2]),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nand3_1 _108_ (
    .A(alu_control[1]),
    .B(alu_control[0]),
    .C(_029_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nor3_1 _109_ (
    .A(\IFU_module.PC [2]),
    .B(\IFU_module.PC [3]),
    .C(\IFU_module.PC [4]),
    .Y(_031_)
  );
  sky130_fd_sc_hd__or3_1 _110_ (
    .A(\IFU_module.PC [2]),
    .B(\IFU_module.PC [3]),
    .C(\IFU_module.PC [4]),
    .X(_032_)
  );
  sky130_fd_sc_hd__nand2_1 _111_ (
    .A(\IFU_module.PC [3]),
    .B(\IFU_module.PC [4]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand2_1 _112_ (
    .A(_032_),
    .B(_033_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__mux2i_1 _113_ (
    .A0(\IFU_module.instr_mem.Memory[0] [5]),
    .A1(\IFU_module.instr_mem.Memory[0] [7]),
    .S(_034_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__mux2i_1 _114_ (
    .A0(_027_),
    .A1(_028_),
    .S(_034_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__o21bai_1 _115_ (
    .A1(\IFU_module.PC [2]),
    .A2(\IFU_module.PC [3]),
    .B1_N(\IFU_module.PC [4]),
    .Y(_037_)
  );
  sky130_fd_sc_hd__mux2i_1 _116_ (
    .A0(\IFU_module.instr_mem.Memory[0] [7]),
    .A1(\IFU_module.instr_mem.Memory[0] [5]),
    .S(_037_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__mux2i_1 _117_ (
    .A0(_028_),
    .A1(_027_),
    .S(_037_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nand2_1 _118_ (
    .A(_028_),
    .B(_031_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nand2_1 _119_ (
    .A(\IFU_module.PC [2]),
    .B(\IFU_module.PC [3]),
    .Y(_041_)
  );
  sky130_fd_sc_hd__and3b_1 _120_ (
    .A_N(\IFU_module.PC [4]),
    .B(\IFU_module.PC [3]),
    .C(\IFU_module.PC [2]),
    .X(_042_)
  );
  sky130_fd_sc_hd__nand3b_1 _121_ (
    .A_N(\IFU_module.PC [4]),
    .B(\IFU_module.PC [2]),
    .C(\IFU_module.instr_mem.Memory[0] [5]),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nand4bb_1 _122_ (
    .A_N(\IFU_module.PC [2]),
    .B_N(\IFU_module.PC [3]),
    .C(\IFU_module.PC [4]),
    .D(\IFU_module.instr_mem.Memory[0] [7]),
    .Y(_044_)
  );
  sky130_fd_sc_hd__a21boi_0 _123_ (
    .A1(\IFU_module.instr_mem.Memory[0] [5]),
    .A2(_042_),
    .B1_N(_044_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__and3_1 _124_ (
    .A(\IFU_module.instr_mem.Memory[0] [5]),
    .B(\IFU_module.PC [3]),
    .C(\IFU_module.PC [4]),
    .X(_046_)
  );
  sky130_fd_sc_hd__and3b_1 _125_ (
    .A_N(\IFU_module.PC [3]),
    .B(\IFU_module.instr_mem.Memory[0] [7]),
    .C(\IFU_module.PC [2]),
    .X(_047_)
  );
  sky130_fd_sc_hd__nor4bb_1 _126_ (
    .A(\IFU_module.PC [2]),
    .B(\IFU_module.PC [4]),
    .C_N(\IFU_module.PC [3]),
    .D_N(\IFU_module.instr_mem.Memory[0] [5]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nor4_1 _127_ (
    .A(_031_),
    .B(_046_),
    .C(_047_),
    .D(_048_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__a21boi_0 _128_ (
    .A1(_045_),
    .A2(_049_),
    .B1_N(_040_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__a22o_1 _129_ (
    .A1(_028_),
    .A2(_031_),
    .B1(_045_),
    .B2(_049_),
    .X(_051_)
  );
  sky130_fd_sc_hd__a21oi_1 _130_ (
    .A1(_038_),
    .A2(_051_),
    .B1(_035_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nor4bb_1 _131_ (
    .A(\IFU_module.PC [3]),
    .B(\IFU_module.PC [4]),
    .C_N(\IFU_module.instr_mem.Memory[0] [5]),
    .D_N(\IFU_module.PC [2]),
    .Y(_053_)
  );
  sky130_fd_sc_hd__and3b_1 _132_ (
    .A_N(\IFU_module.PC [2]),
    .B(\IFU_module.PC [3]),
    .C(\IFU_module.instr_mem.Memory[0] [7]),
    .X(_054_)
  );
  sky130_fd_sc_hd__nand3_1 _133_ (
    .A(\IFU_module.instr_mem.Memory[0] [5]),
    .B(\IFU_module.PC [2]),
    .C(\IFU_module.PC [4]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__or4b_1 _134_ (
    .A(_031_),
    .B(_053_),
    .C(_054_),
    .D_N(_055_),
    .X(_056_)
  );
  sky130_fd_sc_hd__nand4_1 _135_ (
    .A(_032_),
    .B(_043_),
    .C(_044_),
    .D(_055_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nor2_1 _136_ (
    .A(_054_),
    .B(_057_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__o21ai_0 _137_ (
    .A1(_054_),
    .A2(_057_),
    .B1(_040_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__or3_1 _138_ (
    .A(_038_),
    .B(_051_),
    .C(_058_),
    .X(_060_)
  );
  sky130_fd_sc_hd__nand2_1 _139_ (
    .A(_051_),
    .B(_059_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__a21oi_1 _140_ (
    .A1(_051_),
    .A2(_059_),
    .B1(_038_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nand2b_1 _141_ (
    .A_N(_062_),
    .B(_035_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _142_ (
    .A1_N(_052_),
    .A2_N(_060_),
    .B1(_062_),
    .B2(_036_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__a211o_1 _143_ (
    .A1(_039_),
    .A2(_058_),
    .B1(_051_),
    .C1(_036_),
    .X(_065_)
  );
  sky130_fd_sc_hd__o211ai_1 _144_ (
    .A1(_039_),
    .A2(_059_),
    .B1(_051_),
    .C1(_036_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nand2_1 _145_ (
    .A(_065_),
    .B(_066_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand2_1 _146_ (
    .A(_027_),
    .B(\IFU_module.instr_mem.Memory[0] [7]),
    .Y(_068_)
  );
  sky130_fd_sc_hd__o21a_1 _147_ (
    .A1(_051_),
    .A2(_058_),
    .B1(_038_),
    .X(_069_)
  );
  sky130_fd_sc_hd__nand3_1 _148_ (
    .A(_045_),
    .B(_049_),
    .C(_056_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__a221oi_1 _149_ (
    .A1(_061_),
    .A2(_069_),
    .B1(_070_),
    .B2(_039_),
    .C1(_035_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__a21oi_1 _150_ (
    .A1(_050_),
    .A2(_058_),
    .B1(_038_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__a211oi_1 _151_ (
    .A1(_038_),
    .A2(_059_),
    .B1(_072_),
    .C1(_036_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nor2_1 _152_ (
    .A(_071_),
    .B(_073_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__or2_0 _153_ (
    .A(_071_),
    .B(_073_),
    .X(_075_)
  );
  sky130_fd_sc_hd__a21o_1 _154_ (
    .A1(_038_),
    .A2(_070_),
    .B1(_035_),
    .X(_076_)
  );
  sky130_fd_sc_hd__o32a_1 _155_ (
    .A1(_036_),
    .A2(_038_),
    .A3(_061_),
    .B1(_072_),
    .B2(_076_),
    .X(_077_)
  );
  sky130_fd_sc_hd__o32ai_1 _156_ (
    .A1(_036_),
    .A2(_038_),
    .A3(_061_),
    .B1(_072_),
    .B2(_076_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__mux2i_1 _157_ (
    .A0(_064_),
    .A1(_077_),
    .S(\IFU_module.instr_mem.Memory[0] [5]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nor2_1 _158_ (
    .A(\IFU_module.instr_mem.Memory[0] [5]),
    .B(_077_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__o21ai_0 _159_ (
    .A1(_071_),
    .A2(_073_),
    .B1(\IFU_module.instr_mem.Memory[0] [5]),
    .Y(_081_)
  );
  sky130_fd_sc_hd__o31ai_1 _160_ (
    .A1(\IFU_module.instr_mem.Memory[0] [5]),
    .A2(_071_),
    .A3(_073_),
    .B1(_067_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__o31ai_1 _161_ (
    .A1(_067_),
    .A2(_075_),
    .A3(_079_),
    .B1(_082_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__o21ai_0 _162_ (
    .A1(_039_),
    .A2(_050_),
    .B1(_071_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__a22oi_1 _163_ (
    .A1(\IFU_module.instr_mem.Memory[0] [5]),
    .A2(_064_),
    .B1(_081_),
    .B2(_084_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__o311a_1 _164_ (
    .A1(_068_),
    .A2(_075_),
    .A3(_080_),
    .B1(_081_),
    .C1(_067_),
    .X(_086_)
  );
  sky130_fd_sc_hd__nor3_1 _165_ (
    .A(\IFU_module.instr_mem.Memory[0] [5]),
    .B(_052_),
    .C(_063_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__o21ai_0 _166_ (
    .A1(_083_),
    .A2(_087_),
    .B1(_078_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nand2_1 _167_ (
    .A(\IFU_module.instr_mem.Memory[0] [5]),
    .B(\IFU_module.instr_mem.Memory[0] [7]),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nand2b_1 _168_ (
    .A_N(_064_),
    .B(_089_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__a21oi_1 _169_ (
    .A1(_088_),
    .A2(_090_),
    .B1(_030_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nor2_1 _170_ (
    .A(\IFU_module.instr_mem.Memory[0] [5]),
    .B(\IFU_module.instr_mem.Memory[0] [7]),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nor3b_1 _171_ (
    .A(alu_control[0]),
    .B(alu_control[3]),
    .C_N(alu_control[1]),
    .Y(_093_)
  );
  sky130_fd_sc_hd__and2_0 _172_ (
    .A(alu_control[2]),
    .B(_093_),
    .X(_094_)
  );
  sky130_fd_sc_hd__o21ai_0 _173_ (
    .A1(_085_),
    .A2(_086_),
    .B1(_094_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__a211oi_1 _174_ (
    .A1(_030_),
    .A2(_095_),
    .B1(_092_),
    .C1(_063_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nor3_1 _175_ (
    .A(alu_control[1]),
    .B(alu_control[0]),
    .C(alu_control[2]),
    .Y(_097_)
  );
  sky130_fd_sc_hd__xor2_1 _176_ (
    .A(alu_control[3]),
    .B(_097_),
    .X(_098_)
  );
  sky130_fd_sc_hd__xnor2_1 _177_ (
    .A(alu_control[1]),
    .B(alu_control[0]),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nor3_1 _178_ (
    .A(alu_control[3]),
    .B(alu_control[2]),
    .C(_099_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nand4b_1 _179_ (
    .A_N(alu_control[3]),
    .B(alu_control[2]),
    .C(_089_),
    .D(_099_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__a21oi_1 _180_ (
    .A1(_028_),
    .A2(alu_control[3]),
    .B1(_100_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__a211o_1 _181_ (
    .A1(_101_),
    .A2(_102_),
    .B1(_092_),
    .C1(_098_),
    .X(_010_)
  );
  sky130_fd_sc_hd__nor2_1 _182_ (
    .A(_093_),
    .B(_098_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nor2b_1 _183_ (
    .A(_092_),
    .B_N(_094_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nor2_1 _184_ (
    .A(_098_),
    .B(_100_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__o221ai_1 _185_ (
    .A1(_089_),
    .A2(_011_),
    .B1(_013_),
    .B2(_092_),
    .C1(_010_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__nor4_1 _186_ (
    .A(_091_),
    .B(_096_),
    .C(_012_),
    .D(_014_),
    .Y(zero)
  );
  sky130_fd_sc_hd__nand2_1 _187_ (
    .A(\IFU_module.PC [4]),
    .B(_041_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nor2_1 _188_ (
    .A(_027_),
    .B(_015_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__a21oi_1 _189_ (
    .A1(\IFU_module.instr_mem.Memory[0] [7]),
    .A2(_015_),
    .B1(_016_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nand3b_1 _190_ (
    .A_N(\IFU_module.PC [4]),
    .B(\IFU_module.instr_mem.Memory[0] [7]),
    .C(_041_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nand4b_1 _191_ (
    .A_N(_046_),
    .B(_055_),
    .C(_018_),
    .D(_045_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__a21oi_1 _192_ (
    .A1(\IFU_module.instr_mem.Memory[0] [7]),
    .A2(_033_),
    .B1(_046_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nor2_1 _193_ (
    .A(_017_),
    .B(_020_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__mux2i_1 _194_ (
    .A0(_017_),
    .A1(_021_),
    .S(_019_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nand2_1 _195_ (
    .A(_017_),
    .B(_020_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nor3_1 _196_ (
    .A(\IFU_module.instr_mem.Memory[0] [7]),
    .B(_048_),
    .C(_053_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nor3_1 _197_ (
    .A(_019_),
    .B(_022_),
    .C(_023_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__a21oi_1 _198_ (
    .A1(_019_),
    .A2(_022_),
    .B1(_024_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__xor2_1 _199_ (
    .A(_019_),
    .B(_020_),
    .X(_025_)
  );
  sky130_fd_sc_hd__nand2b_1 _200_ (
    .A_N(_024_),
    .B(_025_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nor3b_1 _201_ (
    .A(_078_),
    .B(_067_),
    .C_N(_064_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__a311oi_1 _202_ (
    .A1(_052_),
    .A2(_074_),
    .A3(_026_),
    .B1(\IFU_module.instr_mem.Memory[0] [7]),
    .C1(_027_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__xor2_1 _203_ (
    .A(\IFU_module.PC [2]),
    .B(\IFU_module.PC [3]),
    .X(_001_)
  );
  sky130_fd_sc_hd__nand2b_1 _204_ (
    .A_N(_042_),
    .B(_015_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__clkinv_1 _205_ (
    .A(reset),
    .Y(_007_)
  );
  sky130_fd_sc_hd__clkinv_1 _206_ (
    .A(reset),
    .Y(_008_)
  );
  sky130_fd_sc_hd__dfrtp_1 _207_ (
    .CLK(clock),
    .D(_000_),
    .Q(\IFU_module.PC [2]),
    .RESET_B(_007_)
  );
  sky130_fd_sc_hd__dfrtp_1 _208_ (
    .CLK(clock),
    .D(_001_),
    .Q(\IFU_module.PC [3]),
    .RESET_B(_008_)
  );
  sky130_fd_sc_hd__dfrtp_1 _209_ (
    .CLK(clock),
    .D(_002_),
    .Q(\IFU_module.PC [4]),
    .RESET_B(_009_)
  );
  sky130_fd_sc_hd__udp_dlatch$P _210_ (
    .D(_003_),
    .GATE(_006_),
    .Q(alu_control[0])
  );
  sky130_fd_sc_hd__udp_dlatch$P  _211_ (
    .D(_004_),
    .GATE(_006_),
    .Q(alu_control[1])
  );
  sky130_fd_sc_hd__udp_dlatch$P  _212_ (
    .D(_005_),
    .GATE(_006_),
    .Q(alu_control[2])
  );
  sky130_fd_sc_hd__udp_dlatch$P  _213_ (
    .D(1'h0),
    .GATE(_006_),
    .Q(alu_control[3])
  );
  sky130_fd_sc_hd__udp_dlatch$P  _214_ (
    .D(1'h1),
    .GATE(reset),
    .Q(\IFU_module.instr_mem.Memory[0] [5])
  );
  sky130_fd_sc_hd__udp_dlatch$P  _215_ (
    .D(1'h0),
    .GATE(reset),
    .Q(\IFU_module.instr_mem.Memory[0] [7])
  );
  assign { \IFU_module.PC [31:5], \IFU_module.PC [1:0] } = 29'h00000000;
  assign { \IFU_module.instr_mem.Memory[0] [6], \IFU_module.instr_mem.Memory[0] [4:0] } = { \IFU_module.instr_mem.Memory[0] [7], \IFU_module.instr_mem.Memory[0] [5], \IFU_module.instr_mem.Memory[0] [7], \IFU_module.instr_mem.Memory[0] [7], \IFU_module.instr_mem.Memory[0] [5], \IFU_module.instr_mem.Memory[0] [5] };
endmodule
